### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by PhilM-47** [javisar/ONI-Modloader#10]
I played around with getting this to work in linux and although it didn't work initially, I believe I managed to find the problem.

In ONI-Modloader/Source/Injector/InjectionManager.cs, the path to Assembly-CSharp.dll and the firstpass version have the backslash hardcoded. Linux uses forward slashes, so it is unable to locate the dll's. I believe if you used Path.DirectorySeparatorChar instead, it would work for both operating systems.

**Comment by fistak** [comment]
So does it work after the change? That part was never intended to work on Linux, so there might more issues than this one. I can't really help you much without working Linux environment in this case, but thanks for the interest and good luck ;)

Be sure to fork the repo and submit a Pull Request when you got some progress.

**Comment by PhilM-47** [comment]
The mods directory gets created in the wrong place, but I created mine manually and loaded mods in and was able to use them successfully. I program in a few languages, so can mostly read other languages, but don't actually know c# or have an environment for recompiling and testing it. My best guess is that there's one too many .Parent references on line 132 of ONI-Modloader/Source/Injector/Program.cs as the injector creates the Mods directory in ~/.local/share/Steam/steamapps/common/OxygenNotIncluded/ instead of ~/.local/share/Steam/steamapps/common/

The only other problem I've run into so far was using the liquid and gas tanks. They work just fine during play, but for some reason can't find the classes while reloading a save file. I don't have a windows environment to test in, so haven't been able to tell if that's a unique-to-linux bug.

**Comment by PhilM-47** [comment]
That worked perfectly for the dlls and the Mods directory and no longer needed my workarounds. Thanks!

**Comment by PhilM-47** [comment]
I'm going to have to correct myself. The installer worked perfectly, but the actual mod loader once I run the game seems to still be looking for the Mods folder in the old location (in the common folder). If I create a symbolic link to the Mods dir, it works again, but I'm guessing there's another extra .Parent somewhere.

**Comment by javisar** [comment]
Could you paste here the console output of the injector?

**Comment by PhilM-47** [comment]
I completed deleted the old files from my directories, made steam put back the original dll's, and downloaded the new ones, then ran the injector.

Player log snippet:
```
Platform assembly: /home/PhilM/.local/share/Steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data/Managed/ModLoader.dll (this message is harmless)
Platform assembly: /home/PhilM/.local/share/Steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data/Managed/0Harmony.dll (this message is harmless)
[= INFO =] Initializing Modloader v0.4.0
[= INFO =] Path to mods is: /home/PhilM/.local/share/Steam/steamapps/common/Mods
DirectoryNotFoundException: Directory '/home/PhilM/.local/share/Steam/steamapps/common/Mods' not found.
  at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, FileAttributes mask, FileAttributes attrs) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) [0x00000] in <filename unknown>:0
  at System.IO.DirectoryInfo.GetFiles (System.String searchPattern) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo:GetFiles (string)
  at ModLoader.ModLoader.Start () [0x00000] in <filename unknown>:0
  at ModLoader.Activator.Activate () [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0
  at LaunchInitializer.Awake () [0x00000] in <filename unknown>:0

```
OxygenNotIncluded\Mods\Mod_Log.txt (which also appears to have the hardcoded slashes):
```
[= INFO =] Initializing Modloader v0.4.0
[= INFO =] Path to mods is: /home/PhilM/.local/share/Steam/steamapps/common/Mods
```

**Comment by PhilM-47** [comment]
Console output of injector:
```
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Reading modules: 

/Assembly-CSharp.dll
/Assembly-CSharp-firstpass.dll

Done! Patch Sucessful.
OSVersion: Unix 4.4.0.130
PlatformID: Unix
Creating mods folder is: /home/PhilM/.local/share/Steam/steamapps/common/OxygenNotIncluded/Mods

Press any key to continue . . . 
```

**Comment by javisar** [comment]
Mods folder should be in
/home/PhilM/.local/share/Steam/steamapps/common/OxygenNotIncluded/Mods/

I've updated the the branch, with one less "Parent":
https://github.com/javisar/ONI-Modloader/blob/LinuxCompatibility/Managed/ModLoader.dll

**Comment by PhilM-47** [comment]
That fixed it it for me. Everything loads cleanly now and my mods are working again.

**Comment by javisar** [comment]
Thanks @PhilM-47, I'll close the issue.

**Comment by Gfurst** [comment]
Hello, sorry to to the thread, but I rather ask here instead of opening a different issue, but what happened to the linux branch? And in case its the same, how do you apply them in linux?

And also using:
> ~/.local/share/Steam/steamapps/common/
is not good practice, I for one don't keep my steam library in local files, using `./` is a better abbreviation for the local directory, assuming the installer runs from the same, having a custom input is also a good possibility.

**Comment by javisar** [comment]
I merged the Linux branch into the master branch. To apply it, it's the same procedure as in Windows. Follow
https://github.com/javisar/ONI-Modloader/blob/master/README.md#installation
Let me know if it works for you, I don't have Linux and I work blind with this.

Not sure what you mean with that Linux steam path.

**Comment by Gfurst** [comment]
> Not sure what you mean with that Linux steam path.

Sorry I badly formatted that, but what I meant is that it seemed you guys used that path into some hardcorded of standard thing, I'm just mentioning that may not always be the path of the steam library nor where the game may be.

**Comment by Gfurst** [comment]
Just back to state, yeah you can run it with mono and seems to be working alright, tested a few mods though it doesn't seem to produce a log.

**Comment by javisar** [comment]
All paths in Injector and Modloader are relative and not hardcoded. I'm not sure where you refer, have you seen anything weird in the code? They should work independently of the game location.

Not sure where the logs dump in Linux. In windows is in 'C:\Users\jsromero\AppData\LocalLow\Klei\Oxygen Not Included\output_log.txt'. I guess in linux must be a folder in HOME\.Klei\ or something like that. Let me know if you find it so I can update the README.

Also in order to update the README, which step in the installation in Linux was different from Windows? 

Thank you for the testing.

**Comment by Gfurst** [comment]
It worked fine thanks, I was confused because he was mentioning his own full path. For reference, the linux user files and log:

> $home/.config/unity3d/Klei/Oxygen Not Included/

Then you have player.log in there, and that's the only log I could find though.

What I did, not really different from the readme, I downloaded it directly from the release first of all, unpacked the files into the _Data folder, now whats is really different, is that you can't run the injector directly, you need to run it through mono first: `mono Injector.exe`

[Mono](https://www.mono-project.com/) should be present in most distributions but needs to be installed. Don't exactly know the differences but its basically a different framework implementation of dotnet that works in Linux and others.

**Comment by javisar** [comment]
I think I've found the error in Modloader and fixed it.  Thank you for the feedback.
